services:
  app:
    build:
      context: .
      dockerfile: Dockerfile(fastapi)
    ports:
      - "8383:8383"
    networks:
      - elastic

  nginx:
    build:
      context: .
      dockerfile: Dockerfile(nginx)
    ports:
      - "81:81"
    depends_on:
      - app
    networks:
      - elastic

networks:
  elastic:
    external: true