services:
  app:
    build:
      context: .
      dockerfile: Dockerfile(fastapi)
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8383", "--workers", "4", "--reload"]
    networks:
      - elastic

  nginx:
    build:
      context: .
      dockerfile: Dockerfile(nginx)
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - elastic

networks:
  elastic:
    external: true